######################################################################
# Automatically generated by qmake (2.01a) qui 27. mai 16:59:10 2010
######################################################################

TEMPLATE = subdirs
SUBDIRS = src examples apps
CONFIG += ordered
