######################################################################
# Automatically generated by qmake (2.01a) sáb 17. abr 19:49:36 2010
######################################################################

TEMPLATE = app
TARGET = tsp
DEPENDPATH += ../../../include
INCLUDEPATH += ../../../include
CONFIG = console
DEFINES = 
LIBS = -lgsl -lgslcblas
# Input
SOURCES += tsp.cpp
