######################################################################
# Automatically generated by qmake (2.01a) sáb 17. abr 14:24:39 2010
######################################################################

TEMPLATE = app
TARGET = linalg
DEPENDPATH += ../../../include
INCLUDEPATH += ../../../include
LIBS += -lgsl -lgslcblas
CONFIG = console
DEFINES =

# Input
SOURCES += linalg.cpp
