#ifndef VGTL_GEO_CUBE_HPP
#define VGTL_GEO_CUBE_HPP

/*! \file
 * \brief Geometric cube functions
 */

#include <vgtl/top/cube.hpp>
#include <vgtl/utl/array_cons.hpp>
#include <vgtl/comb/hypercube.hpp>
#include <vgtl/alg/point.hpp>

namespace vgtl {
	
	/*! \addtogroup geo 
	 * @{
	 */

	template <class T, class Point, class BasisIter, class Apply>
	void
	set_cube(T& t, Point p, BasisIter e, Apply& app) {
		const dim_t dim=Dim(T);
		const dim_t n=(1<<dim);
		Vertex(T) v[n];
		for(int i=0; i<n; ++i) {
			v[i]=add(t);
			Point q=p;
			for(int j=0; j<dim; ++j) 
				if(i&(1<<j)) q+=e[j];
			euclidean_point_set(t,v[i],q);
			app.apply(t,v[i]);
		}
		complex_builder<T> cb(t);
		add_cube(cb,&v[0]);
		apply(cb,app);
	}

	//! Adds a hypercube to \c t
	/*! The vertices are generated by hypercube_traverser.
	 */
	template <class T, class Apply>
	Edge(T)
	set_cube(T& t, Apply& app) {
		const dim_t dim=Dim(T);
		const dim_t n=(1<<dim);
		Vertex(T) v[n];
		hypercube_traverser<dim> ht;
		int i=0;
		do {
			v[i]=add(t);
			euclidean_point_set(t,v[i],*ht);
			app.apply(t,v[i]);
			++i;
		} while(++ht);
		complex_builder<T> cb(t);
		add_cube(cb,&v[0]);
		apply(cb,app);
		Edge(T) e=get(cb,_(v[0],v[n-1]));
		return e;
	}

	/*! @} */

}

#endif // VGTL_GEO_CUBE_HPP
