######################################################################
# Automatically generated by qmake (2.01a) sáb 17. abr 14:24:39 2010
######################################################################

TEMPLATE = app
TARGET = quat
DEPENDPATH += ../../../include
INCLUDEPATH += ../../../include
CONFIG = console
DEFINES =

# Input
SOURCES += quat.cpp
