# #####################################################################
# Automatically generated by qmake (2.01a) s�b 17. abr 14:24:39 2010
# #####################################################################
TEMPLATE = app
TARGET = isoview
DEPENDPATH += ../../include
INCLUDEPATH += ../../include
QT += opengl concurrent
LIBS += -lgsl \
    -lgslcblas -L../../lib -lvgtl -lgfortran -lGLU

# Input
SOURCES += isoview.cpp \
    widget.cpp \
    optimize.cpp
HEADERS += data.hpp \
    widget.hpp \
    app.hpp
FORMS += 
