######################################################################
# Automatically generated by qmake (2.01a) sáb 17. abr 16:21:26 2010
######################################################################

TEMPLATE = subdirs

# Input
SUBDIRS += bb linalg pca point quat vec
