# #####################################################################
# Automatically generated by qmake (2.01a) qui 27. mai 16:59:10 2010
# #####################################################################
TEMPLATE = lib
TARGET = vgtl
VERSION = 2.0
DEPENDPATH += . \
    ..\include\vgtl\alg \
    ..\include\vgtl\cg \
    ..\include\vgtl\comb \
    ..\include\vgtl\geo \
    ..\include\vgtl\opt \
    ..\include\vgtl\top \
    ..\include\vgtl\utl \
    ..\include\vgtl\top\iso \
    ..\include\vgtl\top\model
INCLUDEPATH += ..\include
LIBS = -lgfortran
QT -= core \
    gui
DESTDIR = ..\lib
CONFIG = staticlib

# Input
HEADERS += ../include/vgtl/alg/barychange.hpp \
    ../include/vgtl/alg/barygrad.hpp \
    ../include/vgtl/alg/bb.hpp \
    ../include/vgtl/alg/bb_solve.hpp \
    ../include/vgtl/alg/bb_solveJ.hpp \
    ../include/vgtl/alg/bb_solveq.hpp \
    ../include/vgtl/alg/linalg.hpp \
    ../include/vgtl/alg/packed_point.hpp \
    ../include/vgtl/alg/pca.hpp \
    ../include/vgtl/alg/plucker.hpp \
    ../include/vgtl/alg/point.hpp \
    ../include/vgtl/alg/quat.hpp \
    ../include/vgtl/alg/vec.hpp \
    ../include/vgtl/cg/arcball.hpp \
    ../include/vgtl/cg/GL.hpp \
    ../include/vgtl/cg/handles.hpp \
    ../include/vgtl/cg/trackball.hpp \
    ../include/vgtl/comb/binomial.hpp \
    ../include/vgtl/comb/combinations.hpp \
    ../include/vgtl/comb/factorial.hpp \
    ../include/vgtl/comb/hypercube.hpp \
    ../include/vgtl/comb/permutations.hpp \
    ../include/vgtl/comb/range.hpp \
    ../include/vgtl/comb/triangular.hpp \
    ../include/vgtl/geo/bbox.hpp \
    ../include/vgtl/geo/cube.hpp \
    ../include/vgtl/geo/diff_io.hpp \
    ../include/vgtl/geo/diffpars.hpp \
    ../include/vgtl/geo/distance.hpp \
    ../include/vgtl/geo/hctree.hpp \
    ../include/vgtl/geo/hompar.hpp \
    ../include/vgtl/geo/inside.hpp \
    ../include/vgtl/geo/iso.hpp \
    ../include/vgtl/geo/mesh_io.hpp \
    ../include/vgtl/geo/points_io.hpp \
    ../include/vgtl/geo/scalar_io.hpp \
    ../include/vgtl/geo/sort_points.hpp \
    ../include/vgtl/geo/tetra.hpp \
    ../include/vgtl/geo/topological_sort.hpp \
    ../include/vgtl/geo/uniform_triangle.hpp \
    ../include/vgtl/opt/isosimplicial_topology_estimation.hpp \
    ../include/vgtl/opt/lbfgsb01.h \
    ../include/vgtl/opt/lbfgsb01.hpp \
    ../include/vgtl/opt/optimize_diffpars.hpp \
    ../include/vgtl/opt/optimize_diffpars_cb.hpp \
    ../include/vgtl/opt/optimize_hompars_cb.hpp \
    ../include/vgtl/opt/optimize_scalar_cb.hpp \
    ../include/vgtl/opt/optimize_simplex_diffpars.hpp \
    ../include/vgtl/opt/simulated_annealing.hpp \
    ../include/vgtl/top/add.hpp \
    ../include/vgtl/top/add_simplex.hpp \
    ../include/vgtl/top/barycentric.hpp \
    ../include/vgtl/top/complex_buffer.hpp \
    ../include/vgtl/top/complex_buffer_io.hpp \
    ../include/vgtl/top/complex_builder.hpp \
    ../include/vgtl/top/complex_builder_io.hpp \
    ../include/vgtl/top/cube.hpp \
    ../include/vgtl/top/decompose.hpp \
    ../include/vgtl/top/del.hpp \
    ../include/vgtl/top/do_nothing.hpp \
    ../include/vgtl/top/euclidean.hpp \
    ../include/vgtl/top/euler.hpp \
    ../include/vgtl/top/fill.hpp \
    ../include/vgtl/top/grow.hpp \
    ../include/vgtl/top/incidence.hpp \
    ../include/vgtl/top/initial.hpp \
    ../include/vgtl/top/link.hpp \
    ../include/vgtl/top/mark.hpp \
    ../include/vgtl/top/maubach.hpp \
    ../include/vgtl/top/mitchell.hpp \
    ../include/vgtl/top/mt.hpp \
    ../include/vgtl/top/ord_split.hpp \
    ../include/vgtl/top/pm.hpp \
    ../include/vgtl/top/radial.hpp \
    ../include/vgtl/top/reset.hpp \
    ../include/vgtl/top/rivara.hpp \
    ../include/vgtl/top/sc.hpp \
    ../include/vgtl/top/simplex_io.hpp \
    ../include/vgtl/top/star.hpp \
    ../include/vgtl/top/stats.hpp \
    ../include/vgtl/top/subdivide_until.hpp \
    ../include/vgtl/top/top_cell.hpp \
    ../include/vgtl/top/unlink.hpp \
    ../include/vgtl/top/vertices_inv.hpp \
    ../include/vgtl/top/weld.hpp \
    ../include/vgtl/utl/array.hpp \
    ../include/vgtl/utl/array_cons.hpp \
    ../include/vgtl/utl/array_indices.hpp \
    ../include/vgtl/utl/array_io.hpp \
    ../include/vgtl/utl/array_operators.hpp \
    ../include/vgtl/utl/constraint.hpp \
    ../include/vgtl/utl/enable_if.hpp \
    ../include/vgtl/utl/pair_tie.hpp \
    ../include/vgtl/utl/points_io.hpp \
    ../include/vgtl/top/iso/iso.hpp \
    ../include/vgtl/top/iso/triangulate.hpp \
    ../include/vgtl/top/iso/tubular.hpp \
    ../include/vgtl/top/model/bs.hpp \
    ../include/vgtl/top/model/extra_data.hpp \
    ../include/vgtl/top/model/lc.hpp \
    ../include/vgtl/top/model/lc_io.hpp \
    ../include/vgtl/top/model/lmt.hpp \
    ../include/vgtl/top/model/ms.hpp \
    ../include/vgtl/top/model/nmt.hpp \
    ../include/vgtl/top/model/nmt_io.hpp \
    ../include/vgtl/top/model/vc.hpp \
    ../include/vgtl/top/model/vc_io.hpp \
    ../include/vgtl/utl/types.hpp
SOURCES += routines01.f
