######################################################################
# Automatically generated by qmake (2.01a) sáb 17. abr 18:07:35 2010
######################################################################

TEMPLATE = app
TARGET = ziegler_lc
DEPENDPATH += ../../../include
INCLUDEPATH += ../../../include
CONFIG = console
DEFINES =

# Input
SOURCES += ziegler_lc.cpp
